In [ ]:
!pip install ultralytics

Collecting ultralytics
  Downloading ultralytics-8.3.237-py3-none-any.whl.metadata (37 kB)
Requirement already satisfied: numpy>=1.23.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.0.2)
Requirement already satisfied: matplotlib>=3.3.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (3.10.0)
Requirement already satisfied: opencv-python>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (4.12.0.88)
Requirement already satisfied: pillow>=7.1.2 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (11.3.0)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (6.0.3)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.32.4)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (1.16.3)
Requirement already satisfied: torch>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.9.0+cu126)
Requirement already satisfied: torchvision>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (0.24.0+cu126)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (5.9.5)
Requirement already satisfied: polars>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (1.31.0)
Collecting ultralytics-thop>=2.0.18 (from ultralytics)
  Downloading ultralytics_thop-2.0.18-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (4.61.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (2.9.0.post0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (2025.11.12)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.8.0->ultralytics) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.8.0->ultralytics) (3.0.3)
Downloading ultralytics-8.3.237-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 71.7 MB/s eta 0:00:00
Downloading ultralytics_thop-2.0.18-py3-none-any.whl (28 kB)
Installing collected packages: ultralytics-thop, ultralytics
Successfully installed ultralytics-8.3.237 ultralytics-thop-2.0.18

In [ ]:
!pip install torch torchvision
!pip install git+https://github.com/facebookresearch/segment-anything.git

Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.9.0+cpu)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (0.24.0+cpu)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from torchvision) (2.0.2)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from torchvision) (11.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Collecting git+https://github.com/facebookresearch/segment-anything.git
  Cloning https://github.com/facebookresearch/segment-anything.git to /tmp/pip-req-build-suog1k_3
  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/segment-anything.git /tmp/pip-req-build-suog1k_3
  Resolved https://github.com/facebookresearch/segment-anything.git to commit dca509fe793f601edb92606367a655c15ac00fdf
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: segment_anything
  Building wheel for segment_anything (setup.py) ... done
  Created wheel for segment_anything: filename=segment_anything-1.0-py3-none-any.whl size=36592 sha256=0dc5343ec96209720487f4d534fbc4242329cc4e68fd1198baa11e79f80940cf
  Stored in directory: /tmp/pip-ephem-wheel-cache-kv3t4aim/wheels/29/82/ff/04e2be9805a1cb48bec0b85b5a6da6b63f647645750a0e42d4
Successfully built segment_anything
Installing collected packages: segment_anything
Successfully installed segment_anything-1.0

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
from ultralytics import YOLO
import cv2
import numpy as np
from segment_anything import SamPredictor, sam_model_registry
from PIL import Image
import matplotlib.pyplot as plt

In [ ]:
!wget -O /content/sam_vit_b_01ec64.pth https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth

--2025-12-11 12:35:17--  https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth
Resolving dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)... 99.84.41.33, 99.84.41.129, 99.84.41.80, ...
Connecting to dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)|99.84.41.33|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 375042383 (358M) [binary/octet-stream]
Saving to: ‘/content/sam_vit_b_01ec64.pth’

/content/sam_vit_b_ 100%[===================>] 357.67M   262MB/s    in 1.4s

2025-12-11 12:35:18 (262 MB/s) - ‘/content/sam_vit_b_01ec64.pth’ saved [375042383/375042383]

In [ ]:
# =====================================================
# Paths
# =====================================================
images_folder = "/content/drive/My Drive/new grad data/images/train"
output_folder = "/content/drive/My Drive/new grad data/masks/train_masks"
os.makedirs(output_folder, exist_ok=True)

# =====================================================
# Load YOLO Model
# =====================================================
yolo_model = YOLO("/content/drive/My Drive/new grad data/best weights for detection.pt")
yolo_model.to("cuda")

TARGET_CLASS = 0
CONFIDENCE_THRESHOLD = 0.3

# =====================================================
# Load SAM (fast version - vit_b)
# =====================================================
sam_checkpoint = "/content/sam_vit_b_01ec64.pth"
sam = sam_model_registry["vit_b"](checkpoint=sam_checkpoint)
sam.to("cuda")
predictor = SamPredictor(sam)


# =====================================================
# Function to process one image
# =====================================================
def process_and_save_mask(image_path, mask_path):

    image = cv2.imread(image_path)
    if image is None:
        print(f"Cannot read {image_path}")
        return

    # 1) YOLO detection
    det = yolo_model.predict(source=image, verbose=False)[0]

    class_mask = (det.boxes.cls.cpu().numpy() == TARGET_CLASS) & \
                 (det.boxes.conf.cpu().numpy() >= CONFIDENCE_THRESHOLD)

    boxes = det.boxes.xyxy.cpu().numpy()[class_mask]

    if len(boxes) == 0:
        print(f"No valid boxes found → {os.path.basename(image_path)}")
        return

    # 2) SAM segmentation
    predictor.set_image(image)
    H, W = image.shape[:2]
    combined_mask = np.zeros((H, W), dtype=np.uint8)

    for box in boxes:
        x1, y1, x2, y2 = box
        input_box = np.array([x1, y1, x2, y2])

        masks, _, _ = predictor.predict(
            box=input_box,
            multimask_output=False
        )

        combined_mask = np.logical_or(combined_mask, masks[0])

    combined_mask_uint8 = (combined_mask * 255).astype(np.uint8)

    # 3) Save mask
    cv2.imwrite(mask_path, combined_mask_uint8)
    print(f"Saved mask → {mask_path}")


# =====================================================
# LOOP: Process all images in folder
# =====================================================
for img_name in os.listdir(images_folder):

    if not img_name.lower().endswith(('.png', '.jpg', '.jpeg')):
        continue

    img_path = os.path.join(images_folder, img_name)

    name, ext = os.path.splitext(img_name)
    mask_name = f"{name}_mask.png"   # always save as PNG
    mask_path = os.path.join(output_folder, mask_name)

    # -----------------------------------------
    # Skip if mask already exists
    # -----------------------------------------
    if os.path.exists(mask_path):
        print(f"Already processed → {mask_name}")
        continue

    # -----------------------------------------
    # Mask does NOT exist → process it
    # -----------------------------------------
    print(f"Processing new image → {img_name}")
    process_and_save_mask(img_path, mask_path)

print("DONE! All masks processed successfully.")

Streaming output truncated to the last 5000 lines.
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_464_mask.png
Processing new image → 52_frame_519.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_519_mask.png
Processing new image → 52_frame_507.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_507_mask.png
Processing new image → 52_frame_422.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_422_mask.png
Processing new image → 52_frame_420.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_420_mask.png
Processing new image → 52_frame_473.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_473_mask.png
Processing new image → 52_frame_699.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_699_mask.png
Processing new image → 52_frame_677.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_677_mask.png
Processing new image → 52_frame_593.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_593_mask.png
Processing new image → 52_frame_897.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_897_mask.png
Processing new image → 52_frame_908.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_908_mask.png
Processing new image → 52_frame_877.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_877_mask.png
Processing new image → 52_frame_894.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_894_mask.png
Processing new image → 52_frame_693.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_693_mask.png
Processing new image → 52_frame_921.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_921_mask.png
Processing new image → 52_frame_743.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_743_mask.png
Processing new image → 52_frame_865.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_865_mask.png
Processing new image → 52_frame_927.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_927_mask.png
Processing new image → 52_frame_761.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_761_mask.png
Processing new image → 52_frame_618.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_618_mask.png
Processing new image → 52_frame_846.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_846_mask.png
Processing new image → 52_frame_767.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_767_mask.png
Processing new image → 52_frame_831.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_831_mask.png
Processing new image → 52_frame_628.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_628_mask.png
Processing new image → 52_frame_851.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_851_mask.png
Processing new image → 52_frame_81.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_81_mask.png
Processing new image → 52_frame_901.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_901_mask.png
Processing new image → 52_frame_7.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_7_mask.png
Processing new image → 52_frame_884.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_884_mask.png
Processing new image → 52_frame_923.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_923_mask.png
Processing new image → 52_frame_589.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_589_mask.png
Processing new image → 52_frame_915.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_915_mask.png
Processing new image → 52_frame_757.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_757_mask.png
Processing new image → 52_frame_597.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_597_mask.png
Processing new image → 52_frame_664.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_664_mask.png
Processing new image → 52_frame_837.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_837_mask.png
Processing new image → 52_frame_702.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_702_mask.png
Processing new image → 52_frame_77.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_77_mask.png
Processing new image → 52_frame_917.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_917_mask.png
Processing new image → 52_frame_791.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_791_mask.png
Processing new image → 52_frame_706.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_706_mask.png
Processing new image → 52_frame_833.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_833_mask.png
Processing new image → 52_frame_654.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_654_mask.png
Processing new image → 52_frame_78.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_78_mask.png
Processing new image → 52_frame_63.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_63_mask.png
Processing new image → 52_frame_876.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_876_mask.png
Processing new image → 52_frame_736.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_736_mask.png
Processing new image → 52_frame_685.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_685_mask.png
Processing new image → 52_frame_825.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_825_mask.png
Processing new image → 52_frame_926.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_926_mask.png
Processing new image → 52_frame_87.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_87_mask.png
Processing new image → 52_frame_909.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_909_mask.png
Processing new image → 52_frame_868.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_868_mask.png
Processing new image → 52_frame_774.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_774_mask.png
Processing new image → 52_frame_824.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_824_mask.png
Processing new image → 52_frame_641.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_641_mask.png
Processing new image → 52_frame_869.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_869_mask.png
Processing new image → 52_frame_802.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_802_mask.png
Processing new image → 52_frame_631.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_631_mask.png
Processing new image → 52_frame_822.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_822_mask.png
Processing new image → 52_frame_912.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_912_mask.png
Processing new image → 52_frame_708.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_708_mask.png
Processing new image → 52_frame_700.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_700_mask.png
Processing new image → 52_frame_811.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_811_mask.png
Processing new image → 52_frame_599.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_599_mask.png
Processing new image → 52_frame_748.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_748_mask.png
Processing new image → 52_frame_844.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_844_mask.png
Processing new image → 52_frame_800.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_800_mask.png
Processing new image → 52_frame_614.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_614_mask.png
Processing new image → 52_frame_742.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_742_mask.png
Processing new image → 52_frame_874.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_874_mask.png
Processing new image → 52_frame_712.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_712_mask.png
Processing new image → 52_frame_711.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_711_mask.png
Processing new image → 52_frame_839.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_839_mask.png
Processing new image → 52_frame_836.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_836_mask.png
Processing new image → 52_frame_697.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_697_mask.png
Processing new image → 52_frame_858.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_858_mask.png
Processing new image → 52_frame_640.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_640_mask.png
Processing new image → 52_frame_847.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_847_mask.png
Processing new image → 52_frame_809.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_809_mask.png
Processing new image → 52_frame_716.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_716_mask.png
Processing new image → 52_frame_613.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_613_mask.png
Processing new image → 52_frame_634.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_634_mask.png
Processing new image → 52_frame_810.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_810_mask.png
Processing new image → 52_frame_732.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_732_mask.png
Processing new image → 52_frame_66.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_66_mask.png
Processing new image → 52_frame_902.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_902_mask.png
Processing new image → 52_frame_820.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_820_mask.png
Processing new image → 52_frame_707.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_707_mask.png
Processing new image → 52_frame_601.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_601_mask.png
Processing new image → 52_frame_9.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_9_mask.png
Processing new image → 52_frame_864.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_864_mask.png
Processing new image → 52_frame_843.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_843_mask.png
Processing new image → 52_frame_751.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_751_mask.png
Processing new image → 52_frame_807.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_807_mask.png
Processing new image → 52_frame_674.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_674_mask.png
Processing new image → 52_frame_832.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_832_mask.png
Processing new image → 52_frame_609.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_609_mask.png
Processing new image → 52_frame_804.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_804_mask.png
Processing new image → 52_frame_717.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_717_mask.png
Processing new image → 52_frame_788.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_788_mask.png
Processing new image → 52_frame_838.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_838_mask.png
Processing new image → 52_frame_703.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_703_mask.png
Processing new image → 52_frame_662.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_662_mask.png
Processing new image → 52_frame_666.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_666_mask.png
Processing new image → 52_frame_994.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_994_mask.png
Processing new image → 52_frame_988.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_988_mask.png
Processing new image → 52_frame_944.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_944_mask.png
Processing new image → 52_frame_947.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_947_mask.png
Processing new image → 52_frame_93.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_93_mask.png
Processing new image → 52_frame_986.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_986_mask.png
Processing new image → 52_frame_945.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_945_mask.png
Processing new image → 52_frame_962.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_962_mask.png
Processing new image → 52_frame_953.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_953_mask.png
Processing new image → 52_frame_936.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_936_mask.png
Processing new image → 52_frame_939.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_939_mask.png
Processing new image → 52_frame_964.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_964_mask.png
Processing new image → 52_frame_977.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_977_mask.png
Processing new image → 52_frame_932.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_932_mask.png
Processing new image → 52_frame_957.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_957_mask.png
Processing new image → 52_frame_992.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_992_mask.png
Processing new image → 52_frame_987.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_987_mask.png
Processing new image → 52_frame_968.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/52_frame_968_mask.png
Processing new image → 14_frame_1121.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/14_frame_1121_mask.png
Processing new image → 14_frame_1026.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/14_frame_1026_mask.png
Processing new image → 14_frame_1053.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/14_frame_1053_mask.png
Processing new image → 14_frame_1084.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/14_frame_1084_mask.png
Processing new image → 14_frame_1013.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/14_frame_1013_mask.png
Processing new image → 14_frame_1140.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/14_frame_1140_mask.png
Processing new image → 14_frame_1008.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/14_frame_1008_mask.png
Processing new image → 14_frame_1192.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/14_frame_1192_mask.png
Processing new image → 14_frame_101.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/14_frame_101_mask.png
Processing new image → 14_frame_1160.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/14_frame_1160_mask.png
Processing new image → 14_frame_100.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/14_frame_100_mask.png
Processing new image → 14_frame_1091.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/14_frame_1091_mask.png
Processing new image → 14_frame_1023.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/14_frame_1023_mask.png
Processing new image → 14_frame_1278.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/14_frame_1278_mask.png
Processing new image → 14_frame_1205.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/14_frame_1205_mask.png
Processing new image → 14_frame_1188.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/14_frame_1188_mask.png
Processing new image → 14_frame_1212.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/14_frame_1212_mask.png
Processing new image → 14_frame_1198.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/14_frame_1198_mask.png
Processing new image → 14_frame_1219.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/14_frame_1219_mask.png
Processing new image → 14_frame_1104.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/14_frame_1104_mask.png
Processing new image → 14_frame_1015.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/14_frame_1015_mask.png
Processing new image → 14_frame_1187.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/14_frame_1187_mask.png
Processing new image → 14_frame_1093.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/14_frame_1093_mask.png
Processing new image → 14_frame_1112.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/14_frame_1112_mask.png
Processing new image → 14_frame_112.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/14_frame_112_mask.png
Processing new image → 14_frame_117.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/14_frame_117_mask.png
Processing new image → 14_frame_108.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/14_frame_108_mask.png
Processing new image → 14_frame_1159.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/14_frame_1159_mask.png
Processing new image → 14_frame_1195.jpg
Saved mask → /content/drive/My Drive/new grad data/masks/train_masks/14_frame_1195_mask.png
Processing new image → 14_frame_1184.jpg

In [ ]:
# ===========================================
# Paths (Edit according to your folders)
# ===========================================
images_folder = "/content/drive/My Drive/new grad data/images/val"          # Input images folder
output_folder = "/content/drive/My Drive/new grad data/masks/val_masks"     # Folder to save results
os.makedirs(output_folder, exist_ok=True)

# ===========================================
# Load YOLO detection model
# ===========================================
yolo_model = YOLO("/content/drive/My Drive/new grad data/best weights for detection.pt")
yolo_model.to("cuda")


# Target class to segment (0 = first class)
TARGET_CLASS = 0
CONFIDENCE_THRESHOLD = 0.3  # Filter YOLO boxes below this confidence

# ===========================================
# Load SAM model (smaller & faster version)
# ===========================================
sam_checkpoint = "/content/sam_vit_b_01ec64.pth"  # Make sure you have vit_b checkpoint
sam = sam_model_registry["vit_b"](checkpoint=sam_checkpoint)
sam.to("cuda")
predictor = SamPredictor(sam)

# ===========================================
# Process all images in the folder
# ===========================================
for img_name in os.listdir(images_folder):

    # Skip non-image files
    if not img_name.lower().endswith(('.png', '.jpg', '.jpeg')):
        continue

    img_path = os.path.join(images_folder, img_name)
    image = cv2.imread(img_path)
    if image is None:
        print(f"Cannot read {img_name}, skipping...")
        continue

    print(f"Processing: {img_name}")

    # ---------------------------
    # 1) YOLO Detection
    # ---------------------------
    det = yolo_model.predict(source=image, verbose=False)[0]

    # Filter detections by target class and confidence
    class_mask = (det.boxes.cls.cpu().numpy() == TARGET_CLASS) & (det.boxes.conf.cpu().numpy() >= CONFIDENCE_THRESHOLD)
    boxes = det.boxes.xyxy.cpu().numpy()[class_mask]

    if len(boxes) == 0:
        print(f"No confident class {TARGET_CLASS} found in {img_name}")
        continue

    # ---------------------------
    # 2) Prepare SAM for segmentation
    # ---------------------------
    predictor.set_image(image)
    H, W = image.shape[:2]
    combined_mask = np.zeros((H, W), dtype=np.uint8)

    # ---------------------------
    # 3) Generate mask for each detected box
    # ---------------------------
    for box in boxes:
        x1, y1, x2, y2 = box
        input_box = np.array([x1, y1, x2, y2])

        # Run SAM segmentation
        masks, _, _ = predictor.predict(
            box=input_box,
            multimask_output=False
        )

        # Combine masks into one
        combined_mask = np.logical_or(combined_mask, masks[0])

    # Convert boolean mask to uint8
    combined_mask_uint8 = (combined_mask * 255).astype(np.uint8)

    # ---------------------------
    # 4) Save mask
    # ---------------------------
    name, ext = os.path.splitext(img_name)
    save_name = f"{name}_mask.png"  # Always save as PNG
    save_path = os.path.join(output_folder, save_name)
    cv2.imwrite(save_path, combined_mask_uint8)

    print(f"Saved → {save_path}")

print("✔✔ DONE! All masks generated successfully.")

Processing: 14_frame_736.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/14_frame_736_mask.png
Processing: 14_frame_862.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/14_frame_862_mask.png
Processing: 14_frame_763.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/14_frame_763_mask.png
Processing: 14_frame_74.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/14_frame_74_mask.png
Processing: 14_frame_731.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/14_frame_731_mask.png
Processing: 14_frame_764.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/14_frame_764_mask.png
Processing: 14_frame_794.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/14_frame_794_mask.png
Processing: 14_frame_902.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/14_frame_902_mask.png
Processing: 14_frame_916.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/14_frame_916_mask.png
Processing: 14_frame_926.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/14_frame_926_mask.png
Processing: 14_frame_982.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/14_frame_982_mask.png
Processing: 14_frame_891.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/14_frame_891_mask.png
Processing: 14_frame_805.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/14_frame_805_mask.png
Processing: 14_frame_9.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/14_frame_9_mask.png
Processing: 14_frame_770.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/14_frame_770_mask.png
Processing: 14_frame_797.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/14_frame_797_mask.png
Processing: 14_frame_997.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/14_frame_997_mask.png
Processing: 14_frame_740.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/14_frame_740_mask.png
Processing: 14_frame_936.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/14_frame_936_mask.png
Processing: 14_frame_861.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/14_frame_861_mask.png
Processing: 14_frame_944.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/14_frame_944_mask.png
Processing: 14_frame_728.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/14_frame_728_mask.png
Processing: 47_frame_1015.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_1015_mask.png
Processing: 47_frame_1112.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_1112_mask.png
Processing: 47_frame_1019.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_1019_mask.png
Processing: 47_frame_1032.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_1032_mask.png
Processing: 47_frame_1003.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_1003_mask.png
Processing: 47_frame_1040.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_1040_mask.png
Processing: 47_frame_1142.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_1142_mask.png
Processing: 47_frame_1150.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_1150_mask.png
Processing: 47_frame_1114.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_1114_mask.png
Processing: 47_frame_1097.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_1097_mask.png
Processing: 47_frame_1000.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_1000_mask.png
Processing: 47_frame_1394.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_1394_mask.png
Processing: 47_frame_14.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_14_mask.png
Processing: 47_frame_1195.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_1195_mask.png
Processing: 47_frame_1429.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_1429_mask.png
Processing: 47_frame_18.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_18_mask.png
Processing: 47_frame_156.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_156_mask.png
Processing: 47_frame_1388.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_1388_mask.png
Processing: 47_frame_198.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_198_mask.png
Processing: 47_frame_128.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_128_mask.png
Processing: 47_frame_1229.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_1229_mask.png
Processing: 47_frame_1274.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_1274_mask.png
Processing: 47_frame_1352.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_1352_mask.png
Processing: 47_frame_171.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_171_mask.png
Processing: 47_frame_1261.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_1261_mask.png
Processing: 47_frame_159.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_159_mask.png
Processing: 47_frame_1355.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_1355_mask.png
Processing: 47_frame_130.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_130_mask.png
Processing: 47_frame_1270.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_1270_mask.png
Processing: 47_frame_1214.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_1214_mask.png
Processing: 47_frame_1213.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_1213_mask.png
Processing: 47_frame_1239.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_1239_mask.png
Processing: 47_frame_1258.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_1258_mask.png
Processing: 47_frame_1246.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_1246_mask.png
Processing: 47_frame_1196.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_1196_mask.png
Processing: 47_frame_1288.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_1288_mask.png
Processing: 47_frame_1437.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_1437_mask.png
Processing: 47_frame_1167.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_1167_mask.png
Processing: 47_frame_339.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_339_mask.png
Processing: 47_frame_293.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_293_mask.png
Processing: 47_frame_492.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_492_mask.png
Processing: 47_frame_396.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_396_mask.png
Processing: 47_frame_469.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_469_mask.png
Processing: 47_frame_292.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_292_mask.png
Processing: 47_frame_263.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_263_mask.png
Processing: 47_frame_454.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_454_mask.png
Processing: 47_frame_280.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_280_mask.png
Processing: 47_frame_505.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_505_mask.png
Processing: 47_frame_627.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_627_mask.png
Processing: 47_frame_785.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_785_mask.png
Processing: 47_frame_652.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_652_mask.png
Processing: 47_frame_503.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_503_mask.png
Processing: 47_frame_77.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_77_mask.png
Processing: 47_frame_60.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_60_mask.png
Processing: 47_frame_595.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_595_mask.png
Processing: 47_frame_763.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_763_mask.png
Processing: 47_frame_572.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_572_mask.png
Processing: 47_frame_631.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_631_mask.png
Processing: 47_frame_636.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_636_mask.png
Processing: 47_frame_769.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_769_mask.png
Processing: 47_frame_635.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_635_mask.png
Processing: 47_frame_526.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_526_mask.png
Processing: 47_frame_61.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_61_mask.png
Processing: 47_frame_626.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_626_mask.png
Processing: 47_frame_5.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_5_mask.png
Processing: 47_frame_8.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_8_mask.png
Processing: 47_frame_679.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_679_mask.png
Processing: 47_frame_648.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_648_mask.png
Processing: 47_frame_915.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_915_mask.png
Processing: 47_frame_847.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_847_mask.png
Processing: 47_frame_858.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_858_mask.png
Processing: 47_frame_926.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_926_mask.png
Processing: 47_frame_922.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_922_mask.png
Processing: 47_frame_897.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_897_mask.png
Processing: 47_frame_961.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_961_mask.png
Processing: 47_frame_878.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_878_mask.png
Processing: 47_frame_983.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_983_mask.png
Processing: 47_frame_863.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_863_mask.png
Processing: 47_frame_900.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_900_mask.png
Processing: 47_frame_852.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_852_mask.png
Processing: 47_frame_88.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_88_mask.png
Processing: 47_frame_867.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/47_frame_867_mask.png
Processing: 30_frame_1027.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_1027_mask.png
Processing: 30_frame_1200.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_1200_mask.png
Processing: 30_frame_1250.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_1250_mask.png
Processing: 30_frame_1104.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_1104_mask.png
Processing: 30_frame_1188.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_1188_mask.png
Processing: 30_frame_1078.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_1078_mask.png
Processing: 30_frame_1062.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_1062_mask.png
Processing: 30_frame_1265.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_1265_mask.png
Processing: 30_frame_1121.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_1121_mask.png
Processing: 30_frame_1328.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_1328_mask.png
Processing: 30_frame_1182.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_1182_mask.png
Processing: 30_frame_116.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_116_mask.png
Processing: 30_frame_1156.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_1156_mask.png
Processing: 30_frame_1072.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_1072_mask.png
Processing: 30_frame_1288.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_1288_mask.png
Processing: 30_frame_36.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_36_mask.png
Processing: 30_frame_1392.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_1392_mask.png
Processing: 30_frame_369.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_369_mask.png
Processing: 30_frame_175.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_175_mask.png
Processing: 30_frame_166.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_166_mask.png
Processing: 30_frame_328.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_328_mask.png
Processing: 30_frame_1454.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_1454_mask.png
Processing: 30_frame_1440.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_1440_mask.png
Processing: 30_frame_344.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_344_mask.png
Processing: 30_frame_320.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_320_mask.png
Processing: 30_frame_291.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_291_mask.png
Processing: 30_frame_330.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_330_mask.png
Processing: 30_frame_15.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_15_mask.png
Processing: 30_frame_1417.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_1417_mask.png
Processing: 30_frame_1420.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_1420_mask.png
Processing: 30_frame_247.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_247_mask.png
Processing: 30_frame_278.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_278_mask.png
Processing: 30_frame_159.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_159_mask.png
Processing: 30_frame_158.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_158_mask.png
Processing: 30_frame_14.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_14_mask.png
Processing: 30_frame_232.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_232_mask.png
Processing: 30_frame_1444.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_1444_mask.png
Processing: 30_frame_1427.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_1427_mask.png
Processing: 30_frame_1358.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_1358_mask.png
Processing: 30_frame_1350.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_1350_mask.png
Processing: 30_frame_314.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_314_mask.png
Processing: 30_frame_613.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_613_mask.png
Processing: 30_frame_647.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_647_mask.png
Processing: 30_frame_509.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_509_mask.png
Processing: 30_frame_451.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_451_mask.png
Processing: 30_frame_443.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_443_mask.png
Processing: 30_frame_618.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_618_mask.png
Processing: 30_frame_48.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_48_mask.png
Processing: 30_frame_433.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_433_mask.png
Processing: 30_frame_42.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_42_mask.png
Processing: 30_frame_581.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_581_mask.png
Processing: 30_frame_599.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_599_mask.png
Processing: 30_frame_44.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_44_mask.png
Processing: 30_frame_396.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_396_mask.png
Processing: 30_frame_648.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_648_mask.png
Processing: 30_frame_616.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_616_mask.png
Processing: 30_frame_413.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_413_mask.png
Processing: 30_frame_794.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_794_mask.png
Processing: 30_frame_806.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_806_mask.png
Processing: 30_frame_712.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_712_mask.png
Processing: 30_frame_688.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_688_mask.png
Processing: 30_frame_924.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_924_mask.png
Processing: 30_frame_744.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_744_mask.png
Processing: 30_frame_869.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_869_mask.png
Processing: 30_frame_708.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_708_mask.png
Processing: 30_frame_808.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_808_mask.png
Processing: 30_frame_692.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_692_mask.png
Processing: 30_frame_783.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_783_mask.png
Processing: 30_frame_793.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_793_mask.png
Processing: 30_frame_895.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_895_mask.png
Processing: 30_frame_754.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_754_mask.png
Processing: 30_frame_79.jpg
Saved → /content/drive/My Drive/new grad data/masks/val_masks/30_frame_79_mask.png
Processing: 30_frame_84.jpg

In [ ]:
folders = [
    "/content/drive/My Drive/new grad data/images/train",
    "/content/drive/My Drive/new grad data/images/val",
    "/content/drive/My Drive/new grad data/masks/train_masks",
    "/content/drive/My Drive/new grad data/masks/val_masks"
]

def count_images(folder_path):
    count = 0
    for file in os.listdir(folder_path):
        if file.lower().endswith((".png", ".jpg", ".jpeg")):
            count += 1
    return count

total = 0

for folder in folders:
    c = count_images(folder)
    print(f"Folder: {folder} → {c} images")
    total += c

print("\nTotal images in all folders =", total)

Folder: /content/drive/My Drive/new grad data/images/train → 7095 images
Folder: /content/drive/My Drive/new grad data/images/val → 1729 images
Folder: /content/drive/My Drive/new grad data/masks/train_masks → 7045 images
Folder: /content/drive/My Drive/new grad data/masks/val_masks → 1717 images

Total images in all folders = 17586

In [ ]:
# =============================================
# Paths
# =============================================
train_images = "/content/drive/My Drive/new grad data/images/train"
val_images   = "/content/drive/My Drive/new grad data/images/val"

train_masks  = "/content/drive/My Drive/new grad data/masks/train_masks"
val_masks    = "/content/drive/My Drive/new grad data/masks/val_masks"

os.makedirs(train_masks, exist_ok=True)
os.makedirs(val_masks, exist_ok=True)

# ======================================================
# Function: create black mask with same size as image
# ======================================================
def create_black_mask(image_path, save_mask_path):

    img = cv2.imread(image_path)
    if img is None:
        print(f"Error reading {image_path}")
        return

    H, W = img.shape[:2]
    black_mask = np.zeros((H, W), dtype=np.uint8)

    cv2.imwrite(save_mask_path, black_mask)
    print(f"Created black mask → {save_mask_path}")


# ======================================================
# Function: ensure every image has mask
# ======================================================
def ensure_masks(images_folder, masks_folder):

    images = sorted([f for f in os.listdir(images_folder)
                     if f.lower().endswith(('.png','.jpg','.jpeg'))])

    masks = sorted([f for f in os.listdir(masks_folder)
                    if f.lower().endswith(('.png','.jpg','.jpeg','.bmp'))])

    print(f"\nChecking folder:\nImages → {images_folder}\nMasks → {masks_folder}\n")

    img_set = set(images)
    mask_set = set([m.replace("_mask","") for m in masks])   # remove _mask for matching

    for img_name in img_set:

        name, ext = os.path.splitext(img_name)
        mask_name = f"{name}_mask.png"
        mask_path = os.path.join(masks_folder, mask_name)

        if not os.path.exists(mask_path):
            # Mask does NOT exist → create black mask
            create_black_mask(os.path.join(images_folder, img_name), mask_path)

    print("\n Checking done!")


# ======================================================
# Run for train + val
# ======================================================
ensure_masks(train_images, train_masks)
ensure_masks(val_images, val_masks)

print("\n All missing masks have been created!")

Checking folder:
Images → /content/drive/My Drive/new grad data/images/train
Masks → /content/drive/My Drive/new grad data/masks/train_masks

Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1052_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_976_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1140_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1191_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1173_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1206_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1066_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1067_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_978_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1135_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_979_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1123_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1031_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1114_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1209_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1150_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1190_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1017_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1142_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1207_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1024_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1070_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1180_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1130_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1155_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1019_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1184_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1010_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1078_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1117_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_992_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1156_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_999_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1109_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1176_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1125_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1075_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1068_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1072_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1116_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1040_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1161_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_996_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_993_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1065_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1035_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1194_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_985_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1120_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1138_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1049_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1215_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1212_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1076_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1110_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1032_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1197_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/train_masks/23_frame_1081_mask.png

 Checking done!

Checking folder:
Images → /content/drive/My Drive/new grad data/images/val
Masks → /content/drive/My Drive/new grad data/masks/val_masks

Created black mask → /content/drive/My Drive/new grad data/masks/val_masks/23_frame_998_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/val_masks/23_frame_987_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/val_masks/23_frame_1033_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/val_masks/23_frame_1083_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/val_masks/23_frame_1118_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/val_masks/23_frame_1057_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/val_masks/23_frame_1189_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/val_masks/23_frame_980_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/val_masks/23_frame_1051_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/val_masks/23_frame_1077_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/val_masks/23_frame_1028_mask.png
Created black mask → /content/drive/My Drive/new grad data/masks/val_masks/23_frame_1154_mask.png

 Checking done!

 All missing masks have been created!

In [ ]:
folders = [
    "/content/drive/My Drive/new grad data/images/train",
    "/content/drive/My Drive/new grad data/images/val",
    "/content/drive/My Drive/new grad data/masks/train_masks",
    "/content/drive/My Drive/new grad data/masks/val_masks"
]

def count_images(folder_path):
    count = 0
    for file in os.listdir(folder_path):
        if file.lower().endswith((".png", ".jpg", ".jpeg")):
            count += 1
    return count

total = 0

for folder in folders:
    c = count_images(folder)
    print(f"Folder: {folder} → {c} images")
    total += c

print("\nTotal images in all folders =", total)

Folder: /content/drive/My Drive/new grad data/images/train → 7095 images
Folder: /content/drive/My Drive/new grad data/images/val → 1729 images
Folder: /content/drive/My Drive/new grad data/masks/train_masks → 7103 images
Folder: /content/drive/My Drive/new grad data/masks/val_masks → 1729 images

Total images in all folders = 17656

In [ ]:
# ============================================
# Paths
# ============================================
train_images = "/content/drive/My Drive/new grad data/images/train"
val_images   = "/content/drive/My Drive/new grad data/images/val"

train_masks  = "/content/drive/My Drive/new grad data/masks/train_masks"
val_masks    = "/content/drive/My Drive/new grad data/masks/val_masks"


def clean_extra_masks(images_folder, masks_folder):
    print(f"\nChecking folder:\nImages → {images_folder}\nMasks → {masks_folder}")

    # ----------- Get image names (without extension)
    image_files = [f for f in os.listdir(images_folder)
                   if f.lower().endswith(('.png', '.jpg', '.jpeg'))]

    image_names = set(os.path.splitext(f)[0] for f in image_files)

    # ----------- Get mask names (remove _mask suffix)
    mask_files = [f for f in os.listdir(masks_folder)
                  if f.lower().endswith(('.png', '.jpg', '.jpeg'))]

    mask_names = set(os.path.splitext(f)[0].replace("_mask", "") for f in mask_files)

    # ----------- Identify extra masks (masks without images)
    extra_masks = [f for f in mask_files
                   if os.path.splitext(f)[0].replace("_mask", "") not in image_names]

    # ----------- Identify missing masks
    missing_masks = [img for img in image_names
                     if f"{img}_mask.png" not in mask_files and f"{img}_mask.jpg" not in mask_files]

    # ----------- Print summary
    print(f"\nTotal images: {len(image_files)}")
    print(f"Total masks: {len(mask_files)}")
    print(f"Extra masks (will be deleted): {len(extra_masks)}")
    print(f"Missing masks: {len(missing_masks)}")

    # ----------- Delete extra masks
    for mask in extra_masks:
        mask_path = os.path.join(masks_folder, mask)
        os.remove(mask_path)
        print(f"Deleted extra mask → {mask}")

    print("\nCleanup completed.\n")


# =====================================================
# Run cleaning for both train and val
# =====================================================
clean_extra_masks(train_images, train_masks)
clean_extra_masks(val_images, val_masks)

Checking folder:
Images → /content/drive/My Drive/new grad data/images/train
Masks → /content/drive/My Drive/new grad data/masks/train_masks

Total images: 7095
Total masks: 7103
Extra masks (will be deleted): 8
Missing masks: 0
Deleted extra mask → 12_frame_1428_mask (1).png
Deleted extra mask → 12_frame_1343_mask (1).png
Deleted extra mask → 12_frame_329_mask (1).png
Deleted extra mask → 12_frame_541_mask (1).png
Deleted extra mask → 60_frame_614_mask (1).png
Deleted extra mask → 82_frame_873_mask (1).png
Deleted extra mask → 13_frame_582_mask (1).png
Deleted extra mask → 47_frame_546_mask (1).png

Cleanup completed.


Checking folder:
Images → /content/drive/My Drive/new grad data/images/val
Masks → /content/drive/My Drive/new grad data/masks/val_masks

Total images: 1729
Total masks: 1729
Extra masks (will be deleted): 0
Missing masks: 0

Cleanup completed.

In [ ]:
folders = [
    "/content/drive/My Drive/new grad data/images/train",
    "/content/drive/My Drive/new grad data/images/val",
    "/content/drive/My Drive/new grad data/masks/train_masks",
    "/content/drive/My Drive/new grad data/masks/val_masks"
]

def count_images(folder_path):
    count = 0
    for file in os.listdir(folder_path):
        if file.lower().endswith((".png", ".jpg", ".jpeg")):
            count += 1
    return count

total = 0

for folder in folders:
    c = count_images(folder)
    print(f"Folder: {folder} → {c} images")
    total += c

print("\nTotal images in all folders =", total)

Folder: /content/drive/My Drive/new grad data/images/train → 7095 images
Folder: /content/drive/My Drive/new grad data/images/val → 1729 images
Folder: /content/drive/My Drive/new grad data/masks/train_masks → 7095 images
Folder: /content/drive/My Drive/new grad data/masks/val_masks → 1729 images

Total images in all folders = 17648

In [ ]:
import cv2
mask = cv2.imread("/content/drive/My Drive/new grad data/masks/train_masks/11_frame_8_mask.png", cv2.IMREAD_UNCHANGED)
print(mask.shape)

(480, 640)

In [ ]:
import cv2
import numpy as np
mask = cv2.imread("/content/drive/My Drive/new grad data/masks/train_masks/11_frame_8_mask.png", cv2.IMREAD_GRAYSCALE)
print(np.unique(mask))

[  0 255]

In [ ]:
import os

img_folder = "/content/drive/My Drive/new grad data/images/train"
mask_folder = "/content/drive/My Drive/new grad data/masks/train_masks"

imgs = sorted([f for f in os.listdir(img_folder) if f.endswith(('.jpg', '.png'))])
masks = sorted([f for f in os.listdir(mask_folder) if f.endswith('.png')])

for img in imgs:
    mask_name = os.path.splitext(img)[0] + "_mask.png"
    if mask_name not in masks:
        print("Missing mask for:", img)

In [ ]:
import os
import cv2
import numpy as np

# =====================================================
# Folders
# =====================================================
folders = {
    "train": {
        "images": "/content/drive/My Drive/new grad data/images/train",
        "masks":  "/content/drive/My Drive/new grad data/masks/train_masks"
    },
    "val": {
        "images": "/content/drive/My Drive/new grad data/images/val",
        "masks":  "/content/drive/My Drive/new grad data/masks/val_masks"
    }
}

# =====================================================
# Function to fix mask
# =====================================================
def fix_mask(mask_path):
    mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
    if mask is None:
        print(f"Cannot read mask {mask_path}")
        return False

    # Convert any non-zero pixel to 255
    mask[mask > 0] = 255
    cv2.imwrite(mask_path, mask)
    return True

# =====================================================
# Main check
# =====================================================
for split in ["train", "val"]:
    img_folder = folders[split]["images"]
    mask_folder = folders[split]["masks"]

    img_files = sorted([f for f in os.listdir(img_folder) if f.lower().endswith(('.jpg', '.jpeg', '.png'))])
    mask_files = sorted([f for f in os.listdir(mask_folder) if f.lower().endswith('.png')])

    # Check for missing masks
    for img_name in img_files:
        mask_name = os.path.splitext(img_name)[0] + "_mask.png"
        mask_path = os.path.join(mask_folder, mask_name)
        if not os.path.exists(mask_path):
            # create black mask if missing
            img_path = os.path.join(img_folder, img_name)
            img = cv2.imread(img_path)
            if img is not None:
                H, W = img.shape[:2]
                black_mask = np.zeros((H, W), dtype=np.uint8)
                cv2.imwrite(mask_path, black_mask)
                print(f"Created black mask for missing: {mask_name}")
        else:
            # fix mask values
            fix_mask(mask_path)

    # Optional: Remove masks without corresponding images
    for mask_name in mask_files:
        img_name = mask_name.replace("_mask.png", "")
        img_extensions = ['.jpg', '.jpeg', '.png']
        if not any(os.path.exists(os.path.join(img_folder, img_name + ext)) for ext in img_extensions):
            os.remove(os.path.join(mask_folder, mask_name))
            print(f"Removed mask without image: {mask_name}")

print("All masks checked and fixed.")

All masks checked and fixed.

In [ ]:
pip install -U ultralytics

Requirement already satisfied: ultralytics in /usr/local/lib/python3.12/dist-packages (8.3.236)
Requirement already satisfied: numpy>=1.23.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.0.2)
Requirement already satisfied: matplotlib>=3.3.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (3.10.0)
Requirement already satisfied: opencv-python>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (4.12.0.88)
Requirement already satisfied: pillow>=7.1.2 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (11.3.0)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (6.0.3)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.32.4)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (1.16.3)
Requirement already satisfied: torch>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.9.0+cu126)
Requirement already satisfied: torchvision>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (0.24.0+cu126)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (5.9.5)
Requirement already satisfied: polars>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (1.31.0)
Requirement already satisfied: ultralytics-thop>=2.0.18 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.0.18)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (4.61.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (2.9.0.post0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (2025.11.12)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.6)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.8.0->ultralytics) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.8.0->ultralytics) (3.0.3)

In [ ]:
base_folder = "/content/drive/My Drive/new grad data/segmented_labels"
os.makedirs(os.path.join(base_folder, "train_masks_txt"), exist_ok=True)
os.makedirs(os.path.join(base_folder, "val_masks_txt"), exist_ok=True)

In [ ]:
import os
import cv2
import numpy as np

# ===============================
# Paths
# ===============================
train_masks_folder = "/content/drive/My Drive/new grad data/masks/train_masks"
val_masks_folder   = "/content/drive/My Drive/new grad data/masks/val_masks"

train_txt_folder = "/content/drive/My Drive/new grad data/segmented_labels/train_masks_txt"
val_txt_folder   = "/content/drive/My Drive/new grad data/segmented_labels/val_masks_txt"

# Create folders if they don't exist
os.makedirs(train_txt_folder, exist_ok=True)
os.makedirs(val_txt_folder, exist_ok=True)

# ===============================
# Function to convert a mask to YOLO segmentation TXT
# ===============================
def mask_to_yolo_seg(mask_path, txt_path):
    mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
    if mask is None:
        print(f"Cannot read mask: {mask_path}")
        return

    H, W = mask.shape
    # Binarize mask (0 background, 1 object)
    bin_mask = (mask > 0).astype(np.uint8)

    # Find contours
    contours, _ = cv2.findContours(bin_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    lines = []
    for cnt in contours:
        if len(cnt) < 1:
            continue
        # Flatten contour points
        cnt = cnt.reshape(-1, 2)
        x = cnt[:, 0] / W  # normalize x
        y = cnt[:, 1] / H  # normalize y
        # YOLO segmentation format: class_index x1 y1 x2 y2 ...
        coords = ' '.join([f"{xi:.6f} {yi:.6f}" for xi, yi in zip(x, y)])
        lines.append(f"0 {coords}")  # class_index = 0

    # Write TXT (even if empty)
    with open(txt_path, "w") as f:
        f.write("\n".join(lines))

# ===============================
# Process all masks
# ===============================
def process_masks(masks_folder, txt_folder):
    for mask_name in os.listdir(masks_folder):
        if not mask_name.lower().endswith(('.png', '.jpg', '.jpeg')):
            continue

        mask_path = os.path.join(masks_folder, mask_name)
        name, _ = os.path.splitext(mask_name)
        txt_path = os.path.join(txt_folder, f"{name}.txt")

        mask_to_yolo_seg(mask_path, txt_path)

# Process train and val
process_masks(train_masks_folder, train_txt_folder)
process_masks(val_masks_folder, val_txt_folder)

print("DONE! All masks converted to YOLO segmentation format.")

DONE! All masks converted to YOLO segmentation format.

In [ ]:
import os

# Paths to your mask txt folders
train_masks_folder = "/content/drive/My Drive/new grad data/segmented_labels/train_masks_txt"
val_masks_folder   = "/content/drive/My Drive/new grad data/segmented_labels/val_masks_txt"

# Count txt files
train_count = len([f for f in os.listdir(train_masks_folder) if f.lower().endswith('.txt')])
val_count   = len([f for f in os.listdir(val_masks_folder) if f.lower().endswith('.txt')])

print(f"Number of train mask txt files: {train_count}")
print(f"Number of val mask txt files: {val_count}")

Number of train mask txt files: 7095
Number of val mask txt files: 1729

In [ ]:
import os

images_folder = "/content/drive/My Drive/new grad data/images"
masks_folder = "/content/drive/My Drive/new grad data/masks"

images = sorted([f for f in os.listdir(images_folder) if f.lower().endswith((".jpg", ".png", ".jpeg"))])
masks = sorted([f for f in os.listdir(masks_folder) if f.lower().endswith((".txt", ".png", ".jpg"))])

missing_masks = []

for img in images:
    base = os.path.splitext(img)[0]
    expected_mask = base + "_mask"

    # check if mask name appears in any mask file
    found = any(expected_mask in m for m in masks)

    if not found:
        missing_masks.append(img)

print("num og images without masks", len(missing_masks))
print("missing images: ")
for m in missing_masks:
    print(m)

num og images without masks 0
missing images:

In [ ]:
import os

# Paths to your train/val mask folders
train_masks = "/content/drive/My Drive/new grad data/labels/train"
val_masks   = "/content/drive/My Drive/new grad data/labels/val"

def rename_masks(folder):
    for filename in os.listdir(folder):
        if filename.endswith(".txt") and "_mask" in filename:
            old_path = os.path.join(folder, filename)
            new_name = filename.replace("_mask", "")   # remove _mask
            new_path = os.path.join(folder, new_name)

            # Rename the file
            os.rename(old_path, new_path)
            print(f"Renamed: {filename} → {new_name}")

print("Renaming train masks...")
rename_masks(train_masks)

print("\nRenaming val masks...")
rename_masks(val_masks)

Streaming output truncated to the last 5000 lines.
Renamed: 30_frame_1411_mask.txt → 30_frame_1411.txt
Renamed: 30_frame_1404_mask.txt → 30_frame_1404.txt
Renamed: 30_frame_1414_mask.txt → 30_frame_1414.txt
Renamed: 30_frame_143_mask.txt → 30_frame_143.txt
Renamed: 30_frame_1433_mask.txt → 30_frame_1433.txt
Renamed: 30_frame_1424_mask.txt → 30_frame_1424.txt
Renamed: 30_frame_1442_mask.txt → 30_frame_1442.txt
Renamed: 30_frame_1446_mask.txt → 30_frame_1446.txt
Renamed: 30_frame_1456_mask.txt → 30_frame_1456.txt
Renamed: 30_frame_146_mask.txt → 30_frame_146.txt
Renamed: 30_frame_1463_mask.txt → 30_frame_1463.txt
Renamed: 30_frame_1465_mask.txt → 30_frame_1465.txt
Renamed: 30_frame_1437_mask.txt → 30_frame_1437.txt
Renamed: 30_frame_153_mask.txt → 30_frame_153.txt
Renamed: 30_frame_1469_mask.txt → 30_frame_1469.txt
Renamed: 30_frame_154_mask.txt → 30_frame_154.txt
Renamed: 30_frame_157_mask.txt → 30_frame_157.txt
Renamed: 30_frame_160_mask.txt → 30_frame_160.txt
Renamed: 30_frame_162_mask.txt → 30_frame_162.txt
Renamed: 30_frame_163_mask.txt → 30_frame_163.txt
Renamed: 30_frame_169_mask.txt → 30_frame_169.txt
Renamed: 30_frame_17_mask.txt → 30_frame_17.txt
Renamed: 30_frame_167_mask.txt → 30_frame_167.txt
Renamed: 30_frame_170_mask.txt → 30_frame_170.txt
Renamed: 30_frame_171_mask.txt → 30_frame_171.txt
Renamed: 30_frame_187_mask.txt → 30_frame_187.txt
Renamed: 30_frame_19_mask.txt → 30_frame_19.txt
Renamed: 30_frame_190_mask.txt → 30_frame_190.txt
Renamed: 30_frame_179_mask.txt → 30_frame_179.txt
Renamed: 30_frame_194_mask.txt → 30_frame_194.txt
Renamed: 30_frame_198_mask.txt → 30_frame_198.txt
Renamed: 30_frame_201_mask.txt → 30_frame_201.txt
Renamed: 30_frame_202_mask.txt → 30_frame_202.txt
Renamed: 30_frame_210_mask.txt → 30_frame_210.txt
Renamed: 30_frame_21_mask.txt → 30_frame_21.txt
Renamed: 30_frame_224_mask.txt → 30_frame_224.txt
Renamed: 30_frame_221_mask.txt → 30_frame_221.txt
Renamed: 30_frame_22_mask.txt → 30_frame_22.txt
Renamed: 30_frame_226_mask.txt → 30_frame_226.txt
Renamed: 30_frame_228_mask.txt → 30_frame_228.txt
Renamed: 30_frame_231_mask.txt → 30_frame_231.txt
Renamed: 30_frame_233_mask.txt → 30_frame_233.txt
Renamed: 30_frame_234_mask.txt → 30_frame_234.txt
Renamed: 30_frame_235_mask.txt → 30_frame_235.txt
Renamed: 30_frame_238_mask.txt → 30_frame_238.txt
Renamed: 30_frame_243_mask.txt → 30_frame_243.txt
Renamed: 30_frame_249_mask.txt → 30_frame_249.txt
Renamed: 30_frame_251_mask.txt → 30_frame_251.txt
Renamed: 30_frame_252_mask.txt → 30_frame_252.txt
Renamed: 30_frame_253_mask.txt → 30_frame_253.txt
Renamed: 30_frame_260_mask.txt → 30_frame_260.txt
Renamed: 30_frame_261_mask.txt → 30_frame_261.txt
Renamed: 30_frame_256_mask.txt → 30_frame_256.txt
Renamed: 30_frame_264_mask.txt → 30_frame_264.txt
Renamed: 30_frame_269_mask.txt → 30_frame_269.txt
Renamed: 30_frame_270_mask.txt → 30_frame_270.txt
Renamed: 30_frame_281_mask.txt → 30_frame_281.txt
Renamed: 30_frame_289_mask.txt → 30_frame_289.txt
Renamed: 30_frame_292_mask.txt → 30_frame_292.txt
Renamed: 30_frame_30_mask.txt → 30_frame_30.txt
Renamed: 30_frame_274_mask.txt → 30_frame_274.txt
Renamed: 30_frame_302_mask.txt → 30_frame_302.txt
Renamed: 30_frame_295_mask.txt → 30_frame_295.txt
Renamed: 30_frame_303_mask.txt → 30_frame_303.txt
Renamed: 30_frame_311_mask.txt → 30_frame_311.txt
Renamed: 30_frame_306_mask.txt → 30_frame_306.txt
Renamed: 30_frame_315_mask.txt → 30_frame_315.txt
Renamed: 30_frame_313_mask.txt → 30_frame_313.txt
Renamed: 30_frame_319_mask.txt → 30_frame_319.txt
Renamed: 30_frame_326_mask.txt → 30_frame_326.txt
Renamed: 30_frame_329_mask.txt → 30_frame_329.txt
Renamed: 30_frame_33_mask.txt → 30_frame_33.txt
Renamed: 30_frame_331_mask.txt → 30_frame_331.txt
Renamed: 30_frame_338_mask.txt → 30_frame_338.txt
Renamed: 30_frame_343_mask.txt → 30_frame_343.txt
Renamed: 30_frame_340_mask.txt → 30_frame_340.txt
Renamed: 30_frame_347_mask.txt → 30_frame_347.txt
Renamed: 30_frame_351_mask.txt → 30_frame_351.txt
Renamed: 30_frame_35_mask.txt → 30_frame_35.txt
Renamed: 30_frame_356_mask.txt → 30_frame_356.txt
Renamed: 30_frame_358_mask.txt → 30_frame_358.txt
Renamed: 30_frame_359_mask.txt → 30_frame_359.txt
Renamed: 30_frame_363_mask.txt → 30_frame_363.txt
Renamed: 30_frame_364_mask.txt → 30_frame_364.txt
Renamed: 30_frame_365_mask.txt → 30_frame_365.txt
Renamed: 30_frame_367_mask.txt → 30_frame_367.txt
Renamed: 30_frame_370_mask.txt → 30_frame_370.txt
Renamed: 30_frame_375_mask.txt → 30_frame_375.txt
Renamed: 30_frame_38_mask.txt → 30_frame_38.txt
Renamed: 30_frame_379_mask.txt → 30_frame_379.txt
Renamed: 30_frame_39_mask.txt → 30_frame_39.txt
Renamed: 30_frame_391_mask.txt → 30_frame_391.txt
Renamed: 30_frame_381_mask.txt → 30_frame_381.txt
Renamed: 30_frame_392_mask.txt → 30_frame_392.txt
Renamed: 30_frame_393_mask.txt → 30_frame_393.txt
Renamed: 30_frame_397_mask.txt → 30_frame_397.txt
Renamed: 30_frame_405_mask.txt → 30_frame_405.txt
Renamed: 30_frame_418_mask.txt → 30_frame_418.txt
Renamed: 30_frame_423_mask.txt → 30_frame_423.txt
Renamed: 30_frame_426_mask.txt → 30_frame_426.txt
Renamed: 30_frame_425_mask.txt → 30_frame_425.txt
Renamed: 30_frame_435_mask.txt → 30_frame_435.txt
Renamed: 30_frame_437_mask.txt → 30_frame_437.txt
Renamed: 30_frame_440_mask.txt → 30_frame_440.txt
Renamed: 30_frame_441_mask.txt → 30_frame_441.txt
Renamed: 30_frame_444_mask.txt → 30_frame_444.txt
Renamed: 30_frame_457_mask.txt → 30_frame_457.txt
Renamed: 30_frame_452_mask.txt → 30_frame_452.txt
Renamed: 30_frame_459_mask.txt → 30_frame_459.txt
Renamed: 30_frame_460_mask.txt → 30_frame_460.txt
Renamed: 30_frame_462_mask.txt → 30_frame_462.txt
Renamed: 30_frame_463_mask.txt → 30_frame_463.txt
Renamed: 30_frame_465_mask.txt → 30_frame_465.txt
Renamed: 30_frame_469_mask.txt → 30_frame_469.txt
Renamed: 30_frame_470_mask.txt → 30_frame_470.txt
Renamed: 30_frame_471_mask.txt → 30_frame_471.txt
Renamed: 30_frame_474_mask.txt → 30_frame_474.txt
Renamed: 30_frame_476_mask.txt → 30_frame_476.txt
Renamed: 30_frame_480_mask.txt → 30_frame_480.txt
Renamed: 30_frame_486_mask.txt → 30_frame_486.txt
Renamed: 30_frame_492_mask.txt → 30_frame_492.txt
Renamed: 30_frame_493_mask.txt → 30_frame_493.txt
Renamed: 30_frame_500_mask.txt → 30_frame_500.txt
Renamed: 30_frame_5_mask.txt → 30_frame_5.txt
Renamed: 30_frame_506_mask.txt → 30_frame_506.txt
Renamed: 30_frame_514_mask.txt → 30_frame_514.txt
Renamed: 30_frame_516_mask.txt → 30_frame_516.txt
Renamed: 30_frame_518_mask.txt → 30_frame_518.txt
Renamed: 30_frame_540_mask.txt → 30_frame_540.txt
Renamed: 30_frame_523_mask.txt → 30_frame_523.txt
Renamed: 30_frame_542_mask.txt → 30_frame_542.txt
Renamed: 30_frame_545_mask.txt → 30_frame_545.txt
Renamed: 30_frame_546_mask.txt → 30_frame_546.txt
Renamed: 30_frame_55_mask.txt → 30_frame_55.txt
Renamed: 30_frame_550_mask.txt → 30_frame_550.txt
Renamed: 30_frame_552_mask.txt → 30_frame_552.txt
Renamed: 30_frame_554_mask.txt → 30_frame_554.txt
Renamed: 30_frame_553_mask.txt → 30_frame_553.txt
Renamed: 30_frame_567_mask.txt → 30_frame_567.txt
Renamed: 30_frame_562_mask.txt → 30_frame_562.txt
Renamed: 30_frame_571_mask.txt → 30_frame_571.txt
Renamed: 30_frame_576_mask.txt → 30_frame_576.txt
Renamed: 30_frame_587_mask.txt → 30_frame_587.txt
Renamed: 30_frame_586_mask.txt → 30_frame_586.txt
Renamed: 30_frame_580_mask.txt → 30_frame_580.txt
Renamed: 30_frame_589_mask.txt → 30_frame_589.txt
Renamed: 30_frame_591_mask.txt → 30_frame_591.txt
Renamed: 30_frame_60_mask.txt → 30_frame_60.txt
Renamed: 30_frame_602_mask.txt → 30_frame_602.txt
Renamed: 30_frame_601_mask.txt → 30_frame_601.txt
Renamed: 30_frame_608_mask.txt → 30_frame_608.txt
Renamed: 30_frame_603_mask.txt → 30_frame_603.txt
Renamed: 30_frame_61_mask.txt → 30_frame_61.txt
Renamed: 30_frame_611_mask.txt → 30_frame_611.txt
Renamed: 30_frame_617_mask.txt → 30_frame_617.txt
Renamed: 30_frame_622_mask.txt → 30_frame_622.txt
Renamed: 30_frame_627_mask.txt → 30_frame_627.txt
Renamed: 30_frame_63_mask.txt → 30_frame_63.txt
Renamed: 30_frame_630_mask.txt → 30_frame_630.txt
Renamed: 30_frame_636_mask.txt → 30_frame_636.txt
Renamed: 30_frame_640_mask.txt → 30_frame_640.txt
Renamed: 30_frame_639_mask.txt → 30_frame_639.txt
Renamed: 30_frame_644_mask.txt → 30_frame_644.txt
Renamed: 30_frame_653_mask.txt → 30_frame_653.txt
Renamed: 30_frame_654_mask.txt → 30_frame_654.txt
Renamed: 30_frame_674_mask.txt → 30_frame_674.txt
Renamed: 30_frame_671_mask.txt → 30_frame_671.txt
Renamed: 30_frame_675_mask.txt → 30_frame_675.txt
Renamed: 30_frame_681_mask.txt → 30_frame_681.txt
Renamed: 30_frame_677_mask.txt → 30_frame_677.txt
Renamed: 30_frame_683_mask.txt → 30_frame_683.txt
Renamed: 30_frame_685_mask.txt → 30_frame_685.txt
Renamed: 30_frame_655_mask.txt → 30_frame_655.txt
Renamed: 30_frame_697_mask.txt → 30_frame_697.txt
Renamed: 21_frame_1017_mask.txt → 21_frame_1017.txt
Renamed: 21_frame_102_mask.txt → 21_frame_102.txt
Renamed: 21_frame_1027_mask.txt → 21_frame_1027.txt
Renamed: 21_frame_1014_mask.txt → 21_frame_1014.txt
Renamed: 21_frame_1029_mask.txt → 21_frame_1029.txt
Renamed: 21_frame_1031_mask.txt → 21_frame_1031.txt
Renamed: 21_frame_1040_mask.txt → 21_frame_1040.txt
Renamed: 21_frame_1041_mask.txt → 21_frame_1041.txt
Renamed: 21_frame_1044_mask.txt → 21_frame_1044.txt
Renamed: 21_frame_1032_mask.txt → 21_frame_1032.txt
Renamed: 21_frame_1063_mask.txt → 21_frame_1063.txt
Renamed: 21_frame_106_mask.txt → 21_frame_106.txt
Renamed: 21_frame_1064_mask.txt → 21_frame_1064.txt
Renamed: 21_frame_1073_mask.txt → 21_frame_1073.txt
Renamed: 21_frame_1067_mask.txt → 21_frame_1067.txt
Renamed: 21_frame_1076_mask.txt → 21_frame_1076.txt
Renamed: 21_frame_1079_mask.txt → 21_frame_1079.txt
Renamed: 21_frame_1080_mask.txt → 21_frame_1080.txt
Renamed: 21_frame_1081_mask.txt → 21_frame_1081.txt
Renamed: 21_frame_1089_mask.txt → 21_frame_1089.txt
Renamed: 21_frame_1091_mask.txt → 21_frame_1091.txt
Renamed: 21_frame_1107_mask.txt → 21_frame_1107.txt
Renamed: 21_frame_1103_mask.txt → 21_frame_1103.txt
Renamed: 21_frame_1109_mask.txt → 21_frame_1109.txt
Renamed: 21_frame_1111_mask.txt → 21_frame_1111.txt
Renamed: 21_frame_1124_mask.txt → 21_frame_1124.txt
Renamed: 21_frame_1116_mask.txt → 21_frame_1116.txt
Renamed: 21_frame_1112_mask.txt → 21_frame_1112.txt
Renamed: 21_frame_1141_mask.txt → 21_frame_1141.txt
Renamed: 21_frame_1131_mask.txt → 21_frame_1131.txt
Renamed: 21_frame_1144_mask.txt → 21_frame_1144.txt
Renamed: 21_frame_1149_mask.txt → 21_frame_1149.txt
Renamed: 21_frame_1155_mask.txt → 21_frame_1155.txt
Renamed: 21_frame_115_mask.txt → 21_frame_115.txt
Renamed: 21_frame_1157_mask.txt → 21_frame_1157.txt
Renamed: 21_frame_1164_mask.txt → 21_frame_1164.txt
Renamed: 21_frame_1173_mask.txt → 21_frame_1173.txt
Renamed: 21_frame_1163_mask.txt → 21_frame_1163.txt
Renamed: 21_frame_1184_mask.txt → 21_frame_1184.txt
Renamed: 21_frame_1186_mask.txt → 21_frame_1186.txt
Renamed: 21_frame_1185_mask.txt → 21_frame_1185.txt
Renamed: 21_frame_1187_mask.txt → 21_frame_1187.txt
Renamed: 21_frame_1193_mask.txt → 21_frame_1193.txt
Renamed: 21_frame_1194_mask.txt → 21_frame_1194.txt
Renamed: 21_frame_12_mask.txt → 21_frame_12.txt
Renamed: 21_frame_1189_mask.txt → 21_frame_1189.txt
Renamed: 21_frame_1195_mask.txt → 21_frame_1195.txt
Renamed: 21_frame_120_mask.txt → 21_frame_120.txt
Renamed: 21_frame_1201_mask.txt → 21_frame_1201.txt
Renamed: 21_frame_1211_mask.txt → 21_frame_1211.txt
Renamed: 21_frame_1212_mask.txt → 21_frame_1212.txt
Renamed: 21_frame_1209_mask.txt → 21_frame_1209.txt
Renamed: 21_frame_1214_mask.txt → 21_frame_1214.txt
Renamed: 21_frame_1217_mask.txt → 21_frame_1217.txt
Renamed: 21_frame_1240_mask.txt → 21_frame_1240.txt
Renamed: 21_frame_1226_mask.txt → 21_frame_1226.txt
Renamed: 21_frame_1242_mask.txt → 21_frame_1242.txt
Renamed: 21_frame_1241_mask.txt → 21_frame_1241.txt
Renamed: 21_frame_1243_mask.txt → 21_frame_1243.txt
Renamed: 21_frame_1245_mask.txt → 21_frame_1245.txt
Renamed: 21_frame_1248_mask.txt → 21_frame_1248.txt
Renamed: 21_frame_1252_mask.txt → 21_frame_1252.txt
Renamed: 21_frame_1255_mask.txt → 21_frame_1255.txt
Renamed: 21_frame_1267_mask.txt → 21_frame_1267.txt
Renamed: 21_frame_1266_mask.txt → 21_frame_1266.txt
Renamed: 21_frame_1259_mask.txt → 21_frame_1259.txt
Renamed: 21_frame_1273_mask.txt → 21_frame_1273.txt
Renamed: 21_frame_1279_mask.txt → 21_frame_1279.txt
Renamed: 21_frame_128_mask.txt → 21_frame_128.txt
Renamed: 21_frame_1286_mask.txt → 21_frame_1286.txt
Renamed: 21_frame_1288_mask.txt → 21_frame_1288.txt
Renamed: 21_frame_1290_mask.txt → 21_frame_1290.txt
Renamed: 21_frame_1294_mask.txt → 21_frame_1294.txt
Renamed: 21_frame_1295_mask.txt → 21_frame_1295.txt
Renamed: 21_frame_1296_mask.txt → 21_frame_1296.txt
Renamed: 21_frame_1298_mask.txt → 21_frame_1298.txt
Renamed: 21_frame_13_mask.txt → 21_frame_13.txt
Renamed: 21_frame_1308_mask.txt → 21_frame_1308.txt
Renamed: 21_frame_1310_mask.txt → 21_frame_1310.txt
Renamed: 21_frame_1319_mask.txt → 21_frame_1319.txt
Renamed: 21_frame_132_mask.txt → 21_frame_132.txt
Renamed: 21_frame_1320_mask.txt → 21_frame_1320.txt
Renamed: 21_frame_1336_mask.txt → 21_frame_1336.txt
Renamed: 21_frame_1338_mask.txt → 21_frame_1338.txt
Renamed: 21_frame_1333_mask.txt → 21_frame_1333.txt
Renamed: 21_frame_1330_mask.txt → 21_frame_1330.txt
Renamed: 21_frame_1339_mask.txt → 21_frame_1339.txt
Renamed: 21_frame_1340_mask.txt → 21_frame_1340.txt
Renamed: 21_frame_1344_mask.txt → 21_frame_1344.txt
Renamed: 21_frame_1345_mask.txt → 21_frame_1345.txt
Renamed: 21_frame_1349_mask.txt → 21_frame_1349.txt
Renamed: 21_frame_135_mask.txt → 21_frame_135.txt
Renamed: 21_frame_1350_mask.txt → 21_frame_1350.txt
Renamed: 21_frame_1356_mask.txt → 21_frame_1356.txt
Renamed: 21_frame_1358_mask.txt → 21_frame_1358.txt
Renamed: 21_frame_1378_mask.txt → 21_frame_1378.txt
Renamed: 21_frame_1381_mask.txt → 21_frame_1381.txt
Renamed: 21_frame_1383_mask.txt → 21_frame_1383.txt
Renamed: 21_frame_1386_mask.txt → 21_frame_1386.txt
Renamed: 21_frame_1391_mask.txt → 21_frame_1391.txt
Renamed: 21_frame_1393_mask.txt → 21_frame_1393.txt
Renamed: 21_frame_1396_mask.txt → 21_frame_1396.txt
Renamed: 21_frame_1400_mask.txt → 21_frame_1400.txt
Renamed: 21_frame_1404_mask.txt → 21_frame_1404.txt
Renamed: 21_frame_1407_mask.txt → 21_frame_1407.txt
Renamed: 21_frame_141_mask.txt → 21_frame_141.txt
Renamed: 21_frame_1410_mask.txt → 21_frame_1410.txt
Renamed: 21_frame_1412_mask.txt → 21_frame_1412.txt
Renamed: 21_frame_1415_mask.txt → 21_frame_1415.txt
Renamed: 21_frame_1417_mask.txt → 21_frame_1417.txt
Renamed: 21_frame_1422_mask.txt → 21_frame_1422.txt
Renamed: 21_frame_1429_mask.txt → 21_frame_1429.txt
Renamed: 21_frame_1423_mask.txt → 21_frame_1423.txt
Renamed: 21_frame_1437_mask.txt → 21_frame_1437.txt
Renamed: 21_frame_1438_mask.txt → 21_frame_1438.txt
Renamed: 21_frame_1439_mask.txt → 21_frame_1439.txt
Renamed: 21_frame_1398_mask.txt → 21_frame_1398.txt
Renamed: 21_frame_1440_mask.txt → 21_frame_1440.txt
Renamed: 21_frame_1443_mask.txt → 21_frame_1443.txt
Renamed: 21_frame_1447_mask.txt → 21_frame_1447.txt
Renamed: 21_frame_1455_mask.txt → 21_frame_1455.txt
Renamed: 21_frame_1458_mask.txt → 21_frame_1458.txt
Renamed: 21_frame_146_mask.txt → 21_frame_146.txt
Renamed: 21_frame_1460_mask.txt → 21_frame_1460.txt
Renamed: 21_frame_1466_mask.txt → 21_frame_1466.txt
Renamed: 21_frame_147_mask.txt → 21_frame_147.txt
Renamed: 21_frame_149_mask.txt → 21_frame_149.txt
Renamed: 21_frame_15_mask.txt → 21_frame_15.txt
Renamed: 21_frame_158_mask.txt → 21_frame_158.txt
Renamed: 21_frame_155_mask.txt → 21_frame_155.txt
Renamed: 21_frame_16_mask.txt → 21_frame_16.txt
Renamed: 21_frame_162_mask.txt → 21_frame_162.txt
Renamed: 21_frame_163_mask.txt → 21_frame_163.txt
Renamed: 21_frame_168_mask.txt → 21_frame_168.txt
Renamed: 21_frame_169_mask.txt → 21_frame_169.txt
Renamed: 21_frame_17_mask.txt → 21_frame_17.txt
Renamed: 21_frame_174_mask.txt → 21_frame_174.txt
Renamed: 21_frame_175_mask.txt → 21_frame_175.txt
Renamed: 21_frame_177_mask.txt → 21_frame_177.txt
Renamed: 21_frame_188_mask.txt → 21_frame_188.txt
Renamed: 21_frame_179_mask.txt → 21_frame_179.txt
Renamed: 21_frame_189_mask.txt → 21_frame_189.txt
Renamed: 21_frame_192_mask.txt → 21_frame_192.txt
Renamed: 21_frame_193_mask.txt → 21_frame_193.txt
Renamed: 21_frame_2_mask.txt → 21_frame_2.txt
Renamed: 21_frame_203_mask.txt → 21_frame_203.txt
Renamed: 21_frame_213_mask.txt → 21_frame_213.txt
Renamed: 21_frame_217_mask.txt → 21_frame_217.txt
Renamed: 21_frame_22_mask.txt → 21_frame_22.txt
Renamed: 21_frame_23_mask.txt → 21_frame_23.txt
Renamed: 21_frame_225_mask.txt → 21_frame_225.txt
Renamed: 21_frame_214_mask.txt → 21_frame_214.txt
Renamed: 21_frame_249_mask.txt → 21_frame_249.txt
Renamed: 21_frame_251_mask.txt → 21_frame_251.txt
Renamed: 21_frame_244_mask.txt → 21_frame_244.txt
Renamed: 21_frame_256_mask.txt → 21_frame_256.txt
Renamed: 21_frame_263_mask.txt → 21_frame_263.txt
Renamed: 21_frame_262_mask.txt → 21_frame_262.txt
Renamed: 21_frame_264_mask.txt → 21_frame_264.txt
Renamed: 21_frame_275_mask.txt → 21_frame_275.txt
Renamed: 21_frame_260_mask.txt → 21_frame_260.txt
Renamed: 21_frame_283_mask.txt → 21_frame_283.txt
Renamed: 21_frame_281_mask.txt → 21_frame_281.txt
Renamed: 21_frame_285_mask.txt → 21_frame_285.txt
Renamed: 21_frame_29_mask.txt → 21_frame_29.txt
Renamed: 21_frame_290_mask.txt → 21_frame_290.txt
Renamed: 21_frame_291_mask.txt → 21_frame_291.txt
Renamed: 21_frame_3_mask.txt → 21_frame_3.txt
Renamed: 21_frame_304_mask.txt → 21_frame_304.txt
Renamed: 21_frame_31_mask.txt → 21_frame_31.txt
Renamed: 21_frame_32_mask.txt → 21_frame_32.txt
Renamed: 21_frame_321_mask.txt → 21_frame_321.txt
Renamed: 21_frame_320_mask.txt → 21_frame_320.txt
Renamed: 21_frame_325_mask.txt → 21_frame_325.txt
Renamed: 21_frame_329_mask.txt → 21_frame_329.txt
Renamed: 21_frame_330_mask.txt → 21_frame_330.txt
Renamed: 21_frame_34_mask.txt → 21_frame_34.txt
Renamed: 21_frame_340_mask.txt → 21_frame_340.txt
Renamed: 21_frame_347_mask.txt → 21_frame_347.txt
Renamed: 21_frame_348_mask.txt → 21_frame_348.txt
Renamed: 21_frame_35_mask.txt → 21_frame_35.txt
Renamed: 21_frame_350_mask.txt → 21_frame_350.txt
Renamed: 21_frame_353_mask.txt → 21_frame_353.txt
Renamed: 21_frame_355_mask.txt → 21_frame_355.txt
Renamed: 21_frame_378_mask.txt → 21_frame_378.txt
Renamed: 21_frame_385_mask.txt → 21_frame_385.txt
Renamed: 21_frame_358_mask.txt → 21_frame_358.txt
Renamed: 21_frame_38_mask.txt → 21_frame_38.txt
Renamed: 21_frame_390_mask.txt → 21_frame_390.txt
Renamed: 21_frame_394_mask.txt → 21_frame_394.txt
Renamed: 21_frame_397_mask.txt → 21_frame_397.txt
Renamed: 21_frame_399_mask.txt → 21_frame_399.txt
Renamed: 21_frame_401_mask.txt → 21_frame_401.txt
Renamed: 21_frame_402_mask.txt → 21_frame_402.txt
Renamed: 21_frame_406_mask.txt → 21_frame_406.txt
Renamed: 21_frame_420_mask.txt → 21_frame_420.txt
Renamed: 21_frame_409_mask.txt → 21_frame_409.txt
Renamed: 21_frame_430_mask.txt → 21_frame_430.txt
Renamed: 21_frame_43_mask.txt → 21_frame_43.txt
Renamed: 21_frame_431_mask.txt → 21_frame_431.txt
Renamed: 21_frame_442_mask.txt → 21_frame_442.txt
Renamed: 21_frame_448_mask.txt → 21_frame_448.txt
Renamed: 21_frame_445_mask.txt → 21_frame_445.txt
Renamed: 21_frame_453_mask.txt → 21_frame_453.txt
Renamed: 21_frame_466_mask.txt → 21_frame_466.txt
Renamed: 21_frame_47_mask.txt → 21_frame_47.txt
Renamed: 21_frame_468_mask.txt → 21_frame_468.txt
Renamed: 21_frame_469_mask.txt → 21_frame_469.txt
Renamed: 21_frame_46_mask.txt → 21_frame_46.txt
Renamed: 21_frame_470_mask.txt → 21_frame_470.txt
Renamed: 21_frame_471_mask.txt → 21_frame_471.txt
Renamed: 21_frame_472_mask.txt → 21_frame_472.txt
Renamed: 21_frame_473_mask.txt → 21_frame_473.txt
Renamed: 21_frame_477_mask.txt → 21_frame_477.txt
Renamed: 21_frame_486_mask.txt → 21_frame_486.txt
Renamed: 21_frame_481_mask.txt → 21_frame_481.txt
Renamed: 21_frame_483_mask.txt → 21_frame_483.txt
Renamed: 21_frame_49_mask.txt → 21_frame_49.txt
Renamed: 21_frame_489_mask.txt → 21_frame_489.txt
Renamed: 21_frame_5_mask.txt → 21_frame_5.txt
Renamed: 21_frame_501_mask.txt → 21_frame_501.txt

In [ ]:
import os

# Paths
images_folder = "/content/drive/My Drive/new grad data/images/train"
masks_folder  = "/content/drive/My Drive/new grad data/labels/train"

# Get image base names (without extension)
image_names = {os.path.splitext(f)[0] for f in os.listdir(images_folder)
               if f.lower().endswith((".jpg", ".jpeg", ".png"))}

# Get mask base names
mask_names = {os.path.splitext(f)[0] for f in os.listdir(masks_folder)
              if f.lower().endswith(".txt")}

# Find missing masks
missing_masks = image_names - mask_names
# Find masks with no images
extra_masks = mask_names - image_names

print("✔ Total images:", len(image_names))
print("✔ Total masks:", len(mask_names))

print("\n Images WITHOUT masks:")
for name in sorted(missing_masks):
    print(name)

print("\n Masks with NO matching images:")
for name in sorted(extra_masks):
    print(name)

✔ Total images: 7095
✔ Total masks: 7095

 Images WITHOUT masks:

 Masks with NO matching images:

In [ ]:
import os

# Paths
images_folder = "/content/drive/My Drive/new grad data/images/val"
masks_folder  = "/content/drive/My Drive/new grad data/labels/val"

# Get image base names (without extension)
image_names = {os.path.splitext(f)[0] for f in os.listdir(images_folder)
               if f.lower().endswith((".jpg", ".jpeg", ".png"))}

# Get mask base names
mask_names = {os.path.splitext(f)[0] for f in os.listdir(masks_folder)
              if f.lower().endswith(".txt")}

# Find missing masks
missing_masks = image_names - mask_names
# Find masks with no images
extra_masks = mask_names - image_names

print("✔ Total images:", len(image_names))
print("✔ Total masks:", len(mask_names))

print("\n Images WITHOUT masks:")
for name in sorted(missing_masks):
    print(name)

print("\n Masks with NO matching images:")
for name in sorted(extra_masks):
    print(name)

✔ Total images: 1729
✔ Total masks: 1729

 Images WITHOUT masks:

 Masks with NO matching images:

In [ ]:
import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

In [ ]:
from ultralytics import YOLO

# Load segmentation model (pretrained)
model = YOLO("yolov8n-seg.pt")

# Train
results = model.train(
    data="/content/drive/My Drive/new grad data/sperm_dataset_seg.yaml",
    imgsz=640,
    epochs=15,
    batch=16,
    patience=5,
    optimizer="Adam",
    lr0=0.001,
    lrf=0.01,
    weight_decay=0.0005,
    dropout=0.0,

    # Augmentations
    hsv_h=0.015,
    hsv_s=0.7,
    hsv_v=0.4,
    fliplr=0.5,
    mosaic=0.0,
    mixup=0.0,

    # Accelerate training
    device=0,
    workers=4,

    # Saving configs
    project="/content/drive/My Drive/new grad data/segmentation_results",
    name="yolov8_sperm_seg",
    save=True,
    save_period=2,
    exist_ok=True
)

Ultralytics 8.3.237 🚀 Python-3.12.12 torch-2.9.0+cu126 CUDA:0 (Tesla T4, 15095MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/drive/My Drive/new grad data/sperm_dataset_seg.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=15, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.001, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n-seg.pt, momentum=0.937, mosaic=0.0, multi_scale=False, name=yolov8_sperm_seg, nbs=64, nms=False, opset=None, optimize=False, optimizer=Adam, overlap_mask=True, patience=5, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/drive/My Drive/new grad data/segmentation_results, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=/content/drive/My Drive/new grad data/segmentation_results/yolov8_sperm_seg, save_frames=False, save_json=False, save_period=2, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=segment, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=4, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1   1004275  ultralytics.nn.modules.head.Segment          [1, 32, 64, [64, 128, 256]]
YOLOv8n-seg summary: 151 layers, 3,263,811 parameters, 3,263,795 gradients, 11.5 GFLOPs

Transferred 381/417 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n.pt to 'yolo11n.pt': 100% ━━━━━━━━━━━━ 5.4MB 233.0MB/s 0.0s
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.5±0.2 ms, read: 36.6±17.7 MB/s, size: 70.0 KB)
train: Scanning /content/drive/My Drive/new grad data/labels/train.cache... 7095 images, 58 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 7095/7095 9.2Mit/s 0.0s
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.7±0.8 ms, read: 37.7±13.1 MB/s, size: 52.6 KB)
val: Scanning /content/drive/My Drive/new grad data/labels/val.cache... 1729 images, 12 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1729/1729 741.5Kit/s 0.0s
Plotting labels to /content/drive/My Drive/new grad data/segmentation_results/yolov8_sperm_seg/labels.jpg...
optimizer: Adam(lr=0.001, momentum=0.937) with parameter groups 66 weight(decay=0.0), 77 weight(decay=0.0005), 76 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to /content/drive/My Drive/new grad data/segmentation_results/yolov8_sperm_seg
Starting training for 15 epochs...

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
       1/15      3.03G      1.772       2.22      1.309      1.005        142        640: 100% ━━━━━━━━━━━━ 444/444 1.2it/s 6:20
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 55/55 21.5s/it 19:45
                   all       1729      35335      0.788      0.812      0.818      0.419      0.741      0.753      0.751      0.309

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
       2/15      3.44G      1.594      1.912     0.9314     0.9573        157        640: 100% ━━━━━━━━━━━━ 444/444 2.1it/s 3:31
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 55/55 1.8it/s 31.3s
                   all       1729      35335      0.873      0.846      0.895      0.499      0.858      0.832      0.878      0.415

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
       3/15      3.44G       1.52      1.801     0.8278     0.9401        181        640: 100% ━━━━━━━━━━━━ 444/444 2.1it/s 3:30
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 55/55 1.7it/s 31.7s
                   all       1729      35335      0.872       0.86        0.9      0.461      0.792      0.782      0.794      0.295

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
       4/15      3.45G      1.445      1.703     0.7476     0.9274        149        640: 100% ━━━━━━━━━━━━ 444/444 2.1it/s 3:29
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 55/55 1.8it/s 31.1s
                   all       1729      35335       0.91      0.891      0.926      0.548      0.863      0.841       0.87      0.374

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
       5/15      3.46G      1.393      1.636     0.7012     0.9162         90        640: 100% ━━━━━━━━━━━━ 444/444 2.1it/s 3:28
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 55/55 1.7it/s 31.4s
                   all       1729      35335      0.942      0.903      0.946      0.586      0.923      0.883      0.924      0.463
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
       6/15      3.46G      1.352      1.594     0.6667     0.9088         39        640: 100% ━━━━━━━━━━━━ 444/444 2.0it/s 3:37
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 55/55 1.6it/s 33.4s
                   all       1729      35335      0.938      0.914      0.945      0.588      0.904      0.877      0.895      0.399

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
       7/15      3.46G      1.319      1.553     0.6397     0.9031        118        640: 100% ━━━━━━━━━━━━ 444/444 2.1it/s 3:33
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 55/55 1.8it/s 31.4s
                   all       1729      35335      0.949      0.917       0.95      0.616      0.917      0.883       0.91      0.437

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
       8/15      3.46G      1.281      1.504     0.6164     0.8966        140        640: 100% ━━━━━━━━━━━━ 444/444 2.0it/s 3:43
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 55/55 1.7it/s 33.3s
                   all       1729      35335      0.953      0.919      0.954      0.625       0.92      0.881      0.911      0.435

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
       9/15      3.46G       1.26      1.489     0.6031     0.8921         72        640: 100% ━━━━━━━━━━━━ 444/444 2.0it/s 3:39
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 55/55 1.6it/s 33.5s
                   all       1729      35335      0.958       0.92      0.955      0.628      0.914      0.874      0.904      0.425

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
      10/15      3.46G       1.24      1.455     0.5838     0.8892         56        640: 100% ━━━━━━━━━━━━ 444/444 2.0it/s 3:38
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 55/55 1.7it/s 31.5s
                   all       1729      35335      0.962      0.925      0.958       0.64      0.931       0.89      0.919      0.451

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
      11/15      3.46G       1.21       1.43     0.5685     0.8824        171        640: 100% ━━━━━━━━━━━━ 444/444 2.1it/s 3:36
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 55/55 1.7it/s 33.0s
                   all       1729      35335      0.963      0.924      0.959       0.65      0.932      0.888      0.921      0.454

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
      12/15      3.46G       1.19      1.404     0.5563     0.8797         82        640: 100% ━━━━━━━━━━━━ 444/444 2.1it/s 3:36
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 55/55 1.7it/s 32.2s
                   all       1729      35335      0.965      0.931      0.958      0.661      0.932      0.897      0.924      0.466

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
      13/15      3.46G      1.168       1.38     0.5431     0.8753        135        640: 100% ━━━━━━━━━━━━ 444/444 2.1it/s 3:35
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 55/55 1.7it/s 31.6s
                   all       1729      35335      0.966       0.93       0.96      0.667      0.935      0.895      0.924      0.457

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
      14/15      3.46G      1.153      1.364     0.5345      0.872        144        640: 100% ━━━━━━━━━━━━ 444/444 2.1it/s 3:36
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 55/55 1.7it/s 31.4s
                   all       1729      35335      0.967      0.931       0.96      0.669      0.929      0.889       0.92      0.456

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
      15/15      3.46G      1.133      1.343     0.5215     0.8711        119        640: 100% ━━━━━━━━━━━━ 444/444 2.1it/s 3:33
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 55/55 1.8it/s 31.1s
                   all       1729      35335      0.969      0.933      0.962      0.679      0.941        0.9      0.928      0.471

15 epochs completed in 1.399 hours.
Optimizer stripped from /content/drive/My Drive/new grad data/segmentation_results/yolov8_sperm_seg/weights/last.pt, 6.8MB
Optimizer stripped from /content/drive/My Drive/new grad data/segmentation_results/yolov8_sperm_seg/weights/best.pt, 6.8MB

Validating /content/drive/My Drive/new grad data/segmentation_results/yolov8_sperm_seg/weights/best.pt...
Ultralytics 8.3.237 🚀 Python-3.12.12 torch-2.9.0+cu126 CUDA:0 (Tesla T4, 15095MiB)
YOLOv8n-seg summary (fused): 85 layers, 3,258,259 parameters, 0 gradients, 11.3 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 55/55 1.5it/s 37.5s
                   all       1729      35335       0.97      0.933      0.962      0.679       0.94        0.9      0.927      0.471
Speed: 0.2ms preprocess, 2.3ms inference, 0.0ms loss, 3.7ms postprocess per image
Results saved to /content/drive/My Drive/new grad data/segmentation_results/yolov8_sperm_seg

In [ ]:
# model evaluation
from ultralytics import YOLO
import pandas as pd

model_path = "/content/drive/My Drive/new grad data/segmentation_results/yolov8_sperm_seg/weights/best.pt"
model = YOLO(model_path)

In [ ]:
metrics = model.val(
    data="/content/drive/My Drive/new grad data/sperm_dataset.yaml",
    split="val",
    save_json=True,
    imgsz=640
)

Ultralytics 8.3.237 🚀 Python-3.12.12 torch-2.9.0+cu126 CUDA:0 (Tesla T4, 15095MiB)
YOLOv8n-seg summary (fused): 85 layers, 3,258,259 parameters, 0 gradients, 11.3 GFLOPs
val: Fast image access ✅ (ping: 0.3±0.1 ms, read: 34.0±26.9 MB/s, size: 60.7 KB)
val: Scanning /content/drive/My Drive/new grad data/labels/val.cache... 1729 images, 12 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1729/1729 361.9Kit/s 0.0s
requirements: Ultralytics requirement ['faster-coco-eval>=1.6.7'] not found, attempting AutoUpdate...
Using Python 3.12.12 environment at: /usr
Resolved 2 packages in 138ms
Prepared 1 package in 24ms
Installed 1 package in 5ms
 + faster-coco-eval==1.7.0

requirements: AutoUpdate success ✅ 1.1s
WARNING ⚠️ requirements: Restart runtime or rerun command for updates to take effect

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 109/109 1.4it/s 1:20
                   all       1729      35335       0.97      0.933      0.962       0.68       0.97      0.932      0.961      0.521
Speed: 1.2ms preprocess, 3.9ms inference, 0.0ms loss, 3.9ms postprocess per image
Saving /content/runs/segment/val/predictions.json...
Results saved to /content/runs/segment/val

In [ ]:
box_results = {
    "Box_Precision": metrics.box.p,
    "Box_Recall": metrics.box.r,
    "Box_mAP50": metrics.box.map50,
    "Box_mAP50_95": metrics.box.map
}
mask_results = {
    "Mask_Precision": metrics.seg.p,
    "Mask_Recall": metrics.seg.r,
    "Mask_mAP50": metrics.seg.map50,
    "Mask_mAP50_95": metrics.seg.map
}
results = {**box_results, **mask_results}
df = pd.DataFrame([results])
df

,Box_Precision,Box_Recall,Box_mAP50,Box_mAP50_95,Mask_Precision,Mask_Recall,Mask_mAP50,Mask_mAP50_95
0,[0.9695341554015603],[0.9330492124838372],0.961644,0.679559,[0.9700586705271114],[0.9324869849799307],0.960988,0.521446

In [ ]:
csv_path = "/content/drive/My Drive/new grad data/sperm_segmentation_model_results.csv"
df.to_csv(csv_path, index=False)

print(f"Evaluation results saved to: {csv_path}")
df

Evaluation results saved to: /content/drive/My Drive/new grad data/sperm_segmentation_model_results.csv

,Box_Precision,Box_Recall,Box_mAP50,Box_mAP50_95,Mask_Precision,Mask_Recall,Mask_mAP50,Mask_mAP50_95
0,[0.9695341554015603],[0.9330492124838372],0.961644,0.679559,[0.9700586705271114],[0.9324869849799307],0.960988,0.521446

In [ ]:
# compare
from ultralytics import YOLO

def evaluate_model(model_path, data_yaml):
    model = YOLO(model_path)
    metrics = model.val(
        data=data_yaml,
        split="val",
        imgsz=640,
        save_json=False
    )

    return {
        "Box_mAP50": metrics.box.map50,
        "Box_mAP50_95": metrics.box.map,
        "Mask_mAP50": metrics.seg.map50,
        "Mask_mAP50_95": metrics.seg.map
    }

In [ ]:
model_A_path = "/content/drive/My Drive/new grad data/segmentation_results/yolov8_sperm_seg/weights/best.pt"
model_B_path = "/content/seg.pt"

data_yaml = "/content/drive/My Drive/new grad data/sperm_dataset_seg.yaml"

results_A = evaluate_model(model_A_path, data_yaml)
results_B = evaluate_model(model_B_path, data_yaml)

print("Model A Results:", results_A)
print("Model B Results:", results_B)

Ultralytics 8.3.237 🚀 Python-3.12.12 torch-2.9.0+cu126 CUDA:0 (Tesla T4, 15095MiB)
YOLOv8n-seg summary (fused): 85 layers, 3,258,259 parameters, 0 gradients, 11.3 GFLOPs
val: Fast image access ✅ (ping: 0.3±0.1 ms, read: 24.5±10.7 MB/s, size: 53.2 KB)
val: Scanning /content/drive/My Drive/new grad data/labels/val.cache... 1729 images, 12 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1729/1729 1.3Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 109/109 2.2it/s 49.4s
                   all       1729      35335       0.97      0.933      0.962       0.68      0.936      0.896      0.922      0.452
Speed: 1.6ms preprocess, 4.3ms inference, 0.0ms loss, 3.4ms postprocess per image
Results saved to /content/runs/segment/val2
Ultralytics 8.3.237 🚀 Python-3.12.12 torch-2.9.0+cu126 CUDA:0 (Tesla T4, 15095MiB)
YOLOv8n-seg summary (fused): 85 layers, 3,258,649 parameters, 0 gradients, 11.3 GFLOPs
val: Fast image access ✅ (ping: 0.4±0.2 ms, read: 29.8±16.9 MB/s, size: 69.6 KB)
val: Scanning /content/drive/My Drive/new grad data/labels/val.cache... 1729 images, 12 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1729/1729 1.7Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 109/109 3.4it/s 31.8s
                   all       1729      35335          0          0          0          0          0          0          0          0
        Abnormal Sperm       1717      35335          0          0          0          0          0          0          0          0
Speed: 1.9ms preprocess, 4.4ms inference, 0.0ms loss, 1.2ms postprocess per image
Results saved to /content/runs/segment/val3
Model A Results: {'Box_mAP50': np.float64(0.9616444807437063), 'Box_mAP50_95': np.float64(0.6795591194299049), 'Mask_mAP50': np.float64(0.9216301983170759), 'Mask_mAP50_95': np.float64(0.45164788210287793)}
Model B Results: {'Box_mAP50': np.float64(0.0), 'Box_mAP50_95': np.float64(0.0), 'Mask_mAP50': np.float64(0.0), 'Mask_mAP50_95': np.float64(0.0)}

In [ ]:
import pandas as pd

df = pd.DataFrame([
    {"Model": "YOLOv8n-seg", **results_A},
    {"Model": "YOLOv11-seg", **results_B}
])

df

         Model  Box_mAP50  Box_mAP50_95  Mask_mAP50  Mask_mAP50_95
0  YOLOv8n-seg   0.961644      0.679559     0.92163       0.451648
1  YOLOv11-seg   0.000000      0.000000     0.00000       0.000000